MAX_SESSION_CARD_CACHE_SIZE = 10

PARAM_UI_MAP = {
    "API_KEY": "password",
    "温度": "slider",
    "temp": "slider",
    "最大Token": "spinbox",
    "上下文长度": "spinbox",
    "max_new_tokens": "spinbox",
    "top_p": "slider",
    "frequency_penalty": "slider",
    "presence_penalty": "slider",
    "选择模型": "model_selector",
    "启用技能": "checkbox",
}


PARAM_RANGE_MAP = {
    "温度": {"min": 0.0, "max": 2.0, "step": 0.01, "type": "float"},
    "temp": {"min": 0.0, "max": 2.0, "step": 0.01, "type": "float"},
    "最大Token": {"min": 1, "max": 99999999, "step": 1, "type": "int"},
    "上下文长度": {"min": 1, "max": 99999999, "step": 1, "type": "int"},
    "最大新Token": {"min": 1, "max": 18192, "step": 1, "type": "int"},
    "top_p": {"min": 0.0, "max": 1.0, "step": 0.01, "type": "float"},
    "frequency_penalty": {"min": -2.0, "max": 2.0, "step": 0.01, "type": "float"},
    "presence_penalty": {"min": -2.0, "max": 2.0, "step": 0.01, "type": "float"},
}


PROVIDER_MODELS = {
    "MiniMax (月之暗面)": [
        "MiniMax-M2.7",
        "MiniMax-M2.7-highspeed",
        "MiniMax-M2.5",
        "MiniMax-M2.5-highspeed",
        "MiniMax-M2.1",
        "MiniMax-M2.1-highspeed",
    ],
    "SiliconFlow (硅基流动)": [
        "Qwen/Qwen2.5-7B-Instruct",
        "Qwen/Qwen2.5-14B-Instruct",
        "Qwen/Qwen2.5-72B-Instruct",
        "Qwen/Qwen2.5-7B-Instruct-AWQ",
        "THUDM/glm4-9b-chat",
        "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "meta-llama/Meta-Llama-3.1-8B-Instruct",
        "deepseek-ai/DeepSeek-V2-Chat",
        "Qwen/Qwen2-72B-Instruct",
    ],
    "智谱AI": [
        "glm-5.1",
        "glm-5-turbo",
        "glm-4-pro",
        "glm-4-flash",
        "glm-4-flashx",
        "glm-4-plus",
        "glm-4",
    ],
    "DeepSeek": [
        "deepseek-v4-flash",
        "deepseek-v4-pro",
    ],
    "Groq": [
        "openai/gpt-oss-120b",
        "qwen/qwen3-32b",
        "groq/compound",
        "llama-3.3-70b-versatile",
        "meta-llama/llama-4-scout-17b-16e-instruct",
        "moonshotai/kimi-k2-instruct-0905",
    ],
    "百度千帆": [
        "ernie-3.5-8k",
        "ernie-3.5-4k",
        "ernie-speed-8k",
        "ernie-speed-128k",
    ],
    "Ollama": [
        "llama3",
        "llama3.1",
        "qwen2.5",
        "qwen2.5-coder",
        "mistral",
        "phi3",
    ],
    "阿里云 (DashScope)": [
        "qwen3-max",
        "qwen3-plus",
        "qwen3.5-max",
    ],
    "OpenAI": [
        "gpt-4o",
        "gpt-4o-mini",
        "gpt-4-turbo",
        "gpt-4",
        "gpt-3.5-turbo",
    ],
    "Anthropic (Claude)": [
        "claude-sonnet-4-20250514",
        "claude-3-5-sonnet-latest",
        "claude-3-5-haiku-latest",
        "claude-3-opus-latest",
        "claude-3-haiku-latest",
    ],
    "Google Gemini": [
        "gemini-2.5-pro-preview-06-05",
        "gemini-2.0-flash",
        "gemini-1.5-pro",
        "gemini-1.5-flash",
        "gemini-1.5-flash-8b",
    ],
}

FREE_PROVIDERS = {
    "MiniMax (月之暗面)": {
        "API_URL": "https://api.minimax.chat/v1",
        "API_KEY": "",
        "模型名称": "MiniMax-M2.5",
        "温度": 0.7,
        "最大Token": 200000,
        "认证方式": "bearer",
        "获取地址": "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    },
    "SiliconFlow (硅基流动)": {
        "API_URL": "https://api.siliconflow.cn/v1",
        "API_KEY": "",
        "模型名称": "Qwen/Qwen2.5-7B-Instruct",
        "温度": 0.7,
        "最大Token": 200000,
        "认证方式": "bearer",
        "获取地址": "https://cloud.siliconflow.cn/account/ak",
    },
    "阿里云 (DashScope)": {
        "API_URL": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "API_KEY": "",
        "模型名称": "qwen3.5-plus",
        "温度": 0.7,
        "最大Token": 200000,
        "认证方式": "bearer",
        "获取地址": "https://bailian.console.aliyun.com/cn-beijing?tab=model#/api-key",
    },
    "智谱AI": {
        "API_URL": "https://open.bigmodel.cn/api/paas/v4",
        "API_KEY": "",
        "模型名称": "glm-4-flash",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "bearer",
        "获取地址": "https://open.bigmodel.cn/apikey/platform",
    },
    "DeepSeek": {
        "API_URL": "https://api.deepseek.com",
        "API_KEY": "",
        "模型名称": "deepseek-chat",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "bearer",
        "获取地址": "https://platform.deepseek.com/api_keys",
    },
    "Groq": {
        "API_URL": "https://api.groq.com/openai/v1",
        "API_KEY": "",
        "模型名称": "llama-3.1-70b-versatile",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "bearer",
        "获取地址": "https://console.groq.com/keys",
    },
    "百度千帆": {
        "API_URL": "https://qianfan.baidubce.com/v2",
        "API_KEY": "",
        "模型名称": "ernie-3.5-8k",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "bce",
        "获取地址": "https://console.bce.baidu.com/qianfan/ais/console/apikey",
    },
    "Ollama": {
        "API_URL": "http://localhost:11434/v1",
        "API_KEY": "not-needed",
        "模型名称": "llama3",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "none",
        "获取地址": "https://ollama.com",
    },
    "OpenAI": {
        "API_URL": "https://api.openai.com/v1",
        "API_KEY": "",
        "模型名称": "gpt-4o-mini",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "bearer",
        "获取地址": "https://platform.openai.com/api-keys",
    },
    "Anthropic (Claude)": {
        "API_URL": "https://api.anthropic.com/v1",
        "API_KEY": "",
        "模型名称": "claude-sonnet-4-20250514",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "anthropic",
        "获取地址": "https://console.anthropic.com/settings/keys",
    },
    "Google Gemini": {
        "API_URL": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "API_KEY": "",
        "模型名称": "gemini-2.0-flash",
        "温度": 0.7,
        "最大Token": 40960,
        "认证方式": "bearer",
        "获取地址": "https://aistudio.google.com/app/apikey",
    },
}

PROVIDER_ICONS = {
    "MiniMax (月之暗面)": "MiniMax",
    "SiliconFlow (硅基流动)": "siliconflow",
    "阿里云 (DashScope)": "qwen",
    "智谱AI": "智谱",
    "DeepSeek": "deepseek",
    "Groq": "groq",
    "百度千帆": "baidu",
    "Ollama": "Ollama",
    "OpenAI": "大模型",
    "Anthropic (Claude)": "Anthropic",
    "Google Gemini": "gemini-ai",
}
